# Generated by Django 5.0.6 on 2024-06-30 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(choices=[('youth', 'Youth'), ('novice', 'Novice'), ('journeyman', 'Journeyman'), ('master', 'Master'), ('skit', 'Skit'), ('exhibition', 'Strut Your Stuff')], default='novice', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosplay_name', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('judging_time', models.CharField(max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrymanager.division')),
            ],
        ),
    ]
