# Generated by Django 5.0.6 on 2024-07-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='legal_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
