# Generated by Django 5.0.6 on 2024-07-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0003_contestentry_google_entry_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='subentry_number',
        ),
    ]
