# Generated by Django 5.0.6 on 2024-07-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0004_remove_division_subentry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judging_time', models.CharField(choices=[('none', 'Not Assigned'), ('skitonly', 'Skit Entry With No Prejudging'), ('exhibition', 'Strut Your Stuff'), ('072613001400', 'Friday, July 26th, 1pm-2pm'), ('072614001500', 'Friday, July 26th, 2pm-3pm'), ('072615001600', 'Friday, July 26th, 3pm-4pm'), ('072616001700', 'Friday, July 26th, 4pm-5pm'), ('072617001800', 'Friday, July 26th, 5pm-6pm'), ('072710001100', 'Saturday, July 27th, 10am-11am'), ('072711001200', 'Saturday, July 27th, 11am-12pm'), ('072713001400', 'Saturday, July 27th, 1pm-2pm'), ('072714001500', 'Saturday, July 27th, 2pm-3pm')], default='none', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='judging_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrymanager.judgingslot'),
        ),
    ]
