# Generated by Django 5.0.6 on 2024-07-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0005_judgingslot_alter_contestentry_judging_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='email_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
