# Generated by Django 5.0.7 on 2024-07-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0006_contestentry_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_google_entry_number', models.IntegerField(default=0)),
                ('current_novice_number', models.IntegerField(default=0)),
                ('current_journeyman_number', models.IntegerField(default=0)),
                ('current_master_number', models.IntegerField(default=0)),
                ('current_skit_number', models.IntegerField(default=0)),
                ('current_exhibition_number', models.IntegerField(default=0)),
            ],
        ),
    ]
