# Generated by Django 5.0.7 on 2024-07-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0007_internalstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalState',
        ),
        migrations.AddField(
            model_name='contestentry',
            name='internal_division_number',
            field=models.IntegerField(default=0),
        ),
    ]
