# Generated by Django 5.0.7 on 2024-07-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0008_delete_internalstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=50)),
                ('cosplay_name', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrymanager.division')),
            ],
        ),
    ]
