# Generated by Django 5.0.7 on 2024-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0009_hallcontestentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallcontestentry',
            name='division',
            field=models.CharField(choices=[('novice', 'Novice'), ('journeyman', 'Journeyman'), ('master', 'Master')], default='novice', max_length=50),
        ),
    ]
