# Generated by Django 5.0.7 on 2024-08-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrymanager', '0010_alter_hallcontestentry_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='pronouns',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
